### PR TITLE
Simplify linear output and avoid HTML

### PR DESCRIPTION
**Pull request by marians**
### What does this PR do?

This PR removes the linear output to produce readable Markdown content.

### What is the effect of this change to users?

An HTML-heavy output is not likely to be adopted by developers as the default way to fill the Chart's README.md file.

With Markdown formatting that is still readable for the human eye, I hope that we can get people to adopt the linear style.

### How does it look like?

Before: https://github.com/giantswarm/schemadocs/blob/v0.0.6/pkg/generate/testdata/output-linear.txt

After: https://github.com/giantswarm/schemadocs/blob/c16e932a59c602bdc389b7f968bb1bec698dd7c8/pkg/generate/testdata/output_linear.golden

### Should this change be mentioned in the release notes?

- [x] CHANGELOG.md has been updated (if it exists)

### CODE REVIEW

**Comment by marians** [comment]
@pipo02mix WDYT about this change?

**Comment by pipo02mix** [comment]
I did not see final output but I agree with the idea :)

**Comment by marians** [comment]
Pasted some sample code into a preview app for you. [Link](https://www.digitalocean.com/community/markdown#?md=%0A%23%23+Chart+configuration+reference%0A%0A%23%23%23+AWS+settings+%7B%23aws-settings%7D%0A%0A---%0A%0A%60.providerSpecific.ami%60%0A%0A**Type%3A**+%60string%60%0A%0A**Amazon+machine+image+%28AMI%29**%0A%0AIf+specified%2C+this+image+will+be+used+to+provision+EC2+instances.%0A%0A---%0A%0A%60.providerSpecific.awsClusterRoleIdentityName%60%0A%0A**Type%3A**+%60string%60%0A%0A**Cluster+role+identity+name**%0A%0AName+of+an+AWSClusterRoleIdentity+object.+This+in+turn+refers+to+the+IAM+role+used+to+create+all+AWS+cloud+resources+when+creating+the+cluster.+The+role+can+be+in+another+AWS+account+in+order+to+create+all+resources+in+that+account.+Note%3A+This+name+does+not+refer+directly+to+an+IAM+role+name%2FARN.%0A%0A---%0A%0A%60.providerSpecific.flatcarAwsAccount%60%0A%0A**Type%3A**+%60string%60%0A%0A**AWS+account+owning+Flatcar+image**%0A%0AAWS+account+ID+owning+the+Flatcar+Container+Linux+AMI.%0A%0A---%0A%0A%60.providerSpecific.region%60%0A%0A**Type%3A**+%60string%60%0A%0A**Region**%0A%0A%0A%0A%0A%23%23%23+Connectivity+%7B%23connectivity%7D%0A%0A---%0A%0A%60.global.connectivity.availabilityZoneUsageLimit%60%0A%0A**Type%3A**+%60integer%60%0A%0A**Availability+zones**%0A%0AMaximum+number+of+availability+zones+%28AZ%29+that+should+be+used+in+a+region.+If+a+region+has+more+than+this+number+of+AZs+then+this+number+of+AZs+will+be+picked+randomly+when+creating+subnets.%0A%0A---%0A%0A%60.global.connectivity.bastion%60%0A%0A**Type%3A**+%60object%60%0A%0A**Bastion+host**%0A%0A%0A%0A---%0A%0A%60.global.connectivity.bastion.enabled%60%0A%0A**Type%3A**+%60boolean%60%0A%0A**Enable**%0A%0A%0A%0A---%0A%0A%60.global.connectivity.bastion.instanceType%60%0A%0A**Type%3A**+%60string%60%0A%0A**EC2+instance+type**%0A%0A%0A%0A---%0A%0A%60.global.connectivity.bastion.replicas%60%0A%0A**Type%3A**+%60integer%60%0A%0A**Number+of+hosts**%0A%0A%0A%0A---%0A%0A%60.global.connectivity.bastion.subnetTags%60%0A%0A**Type%3A**+%60array%60%0A%0A**Subnet+tags**%0A%0ATags+to+filter+which+AWS+subnets+will+be+used+for+the+bastion+hosts.%0A%0A---%0A%0A%60.global.connectivity.bastion.subnetTags%5B*%5D%60%0A%0A**Type%3A**+%60object%60%0A%0A**Subnet+tag**%0A%0A%0A%0A)

**Review by pipo02mix — APPROVED** [review]
LGTM!

**Pull request merged**
